### ISSUE TITLE
React error on invocation

### ISSUE THREAD

**Issue by dima** [clover/clover-cloud-connector-example#16]
Following steps as per README results in the following error when accessing the resource.

```
example-react.js:2521 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `ConfigureApp`.
    in ConfigureApp (created by bound createElement)
    in bound createElement (created by ConfiguredManualTransactionApp)
    in div (created by ConfiguredManualTransactionApp)
    in ConfiguredManualTransactionApp
```

**Comment by rayramsay** [comment]
We're in the process of end-of-lifing this project, but have updated package.json to specify an earlier version of React that allows createElement. Please reach out to semi-integrations@clover.com if you have more questions. Thank you!

**Comment by dima** [comment]
@rayramsay OK, that was just an FYI. I wasn't aware you are wrapping this example up. I found some useful bits of code here, hope you have something similar that is maintained in the future that shows remote-pay-cloud usage.

**Comment by rayramsay** [comment]
@dima You might also be interested in our new repo, https://github.com/clover/remote-pay-cloud-tutorial and the older https://github.com/clover/clover-cloud-connector-unit-examples
